name: Prometheus Node Exporter Deployment

on:
  push:
    branches:
      - task-7
  workflow_dispatch:

jobs:
  deploy-prometheus:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'

      - name: Configure SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

      - name: Add Prometheus Helm Repositories
        run: |
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo update

      - name: Deploy Prometheus Operator
        run: |
          kubectl config set-cluster k3s --server=${{ secrets.K3S_SERVER_URL }} --certificate-authority-data=${{ secrets.K3S_CA_CERT }}
          kubectl config set-credentials admin --token=${{ secrets.K3S_CLUSTER_TOKEN }}
          kubectl config set-context k3s --cluster=k3s --user=admin
          kubectl config use-context k3s

          # Install Prometheus Operator
          helm upgrade --install prometheus prometheus-community/kube-prometheus-stack \
            --namespace monitoring \
            --create-namespace \
            --set prometheusOperator.createCustomResource=true \
            --set grafana.enabled=true \
            --set alertmanager.enabled=true

      - name: Deploy Node Exporter
        run: |
          # Install Node Exporter
          helm upgrade --install node-exporter prometheus-community/prometheus-node-exporter \
            --namespace monitoring \
            --set hostRootfs=true \
            --set service.type=ClusterIP

      - name: Verify Deployment
        run: |
          kubectl get pods -n monitoring
          kubectl get services -n monitoring
