name: Deploy Prometheus to Kubernetes

on:
  push:
    branches:
      - task-7

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: unnecessary
        if_key_exists: replace

    - name: Adding Known Hosts
      run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3

    - name: Set up Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
        helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
        helm repo update

    - name: Create kubeconfig
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config
        chmod 600 $HOME/.kube/config

    - name: Deploy Prometheus
      run: |
        # Delete existing prometheus releases and resources
        helm uninstall prometheus -n monitoring --ignore-not-found
        helm uninstall prometheus-stack -n monitoring --ignore-not-found
        
        # Delete all related ClusterRoles
        kubectl delete clusterrole prometheus-grafana-clusterrole --ignore-not-found
        kubectl delete clusterrole prometheus-kube-state-metrics --ignore-not-found
        kubectl delete clusterrole prometheus-kube-prometheus-operator --ignore-not-found
        kubectl delete clusterrole prometheus-kube-prometheus-prometheus --ignore-not-found
        kubectl delete clusterrole prometheus-kube-prometheus-alertmanager --ignore-not-found
        
        # Delete related ClusterRoleBindings
        kubectl delete clusterrolebinding prometheus-grafana-clusterrolebinding --ignore-not-found
        kubectl delete clusterrolebinding prometheus-kube-state-metrics --ignore-not-found
        kubectl delete clusterrolebinding prometheus-kube-prometheus-operator --ignore-not-found
        kubectl delete clusterrolebinding prometheus-kube-prometheus-prometheus --ignore-not-found
        kubectl delete clusterrolebinding prometheus-kube-prometheus-alertmanager --ignore-not-found
        
        # Delete the monitoring namespace to ensure clean slate
        kubectl delete namespace monitoring --ignore-not-found
        
        # Wait for resources to be fully deleted
        sleep 45
        
        # Create fresh namespace
        kubectl create namespace monitoring
        
        # Install prometheus with fresh configuration
        helm upgrade --install prometheus prometheus-community/kube-prometheus-stack \
          --namespace monitoring \
          --create-namespace \
          --wait \
          --timeout 15m \
          --set grafana.serviceMonitor.enabled=true \
          --set prometheus.serviceMonitor.enabled=true \
          --set prometheusOperator.serviceMonitor.enabled=true \
          --set alertmanager.serviceMonitor.enabled=true

    - name: Install Node Exporter
      run: |
        helm install node-exporter prometheus-community/prometheus-node-exporter -n monitoring