# File: .github/workflows/ci.yml
name: k3s
on:
  push:
    branches:
      - master
  pull_request:
env:
  KUBECONFIG: ${{ secrets.KUBE_CONFIG }}
jobs:
  k3s:
    name: k3s
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@master
      - name: Set up Docker
        uses: docker/setup-docker@v2
      - name: k3s
        uses: yellowmegaman/k3s-gha@master
        with:
          k3s_tag: latest
          install_kubectl: true
          custom_registry: true
      - name: try to use kubeconfig
        run: kubectl get ns