name: Terraform Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

defaults:
  run:
    working-directory: task_8

jobs:
  terraform-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::051826725870:role/git_action
          aws-region: eu-central-1
          audience: "sts.amazonaws.com"

      - name: Terraform Init
        run: terraform init

      - name: Check Terraform format
        run: terraform fmt -check

      - name: Validate Terraform files
        run: terraform validate


  terraform-plan:
    runs-on: ubuntu-latest
    needs: terraform-check
    permissions:
      id-token: write
      contents: read    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::051826725870:role/git_action
          aws-region: eu-central-1
          audience: "sts.amazonaws.com"


      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: |
          echo "Mock: Terraform Plan would show changes here"
          echo "Plan: 2 to add, 0 to change, 0 to destroy"
          exit 0
        continue-on-error: false


  terraform-apply:
    runs-on: ubuntu-latest
    needs: terraform-plan
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::051826725870:role/git_action
          aws-region: eu-central-1
          audience: "sts.amazonaws.com"

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: |
          echo "Mock: Terraform Apply Workflow"
          echo "Apply complete! Resources: 2 added, 0 changed, 0 destroyed"
          echo "Mock workflow completed successfully!"
          exit 0